openapi: 3.0.3

info:
  title: Locations API
  description: Locations management and location types
  contact:
    name: Proactive Devs team
    email: proactivedevs@gmail.com
    url: 'http://proactivedevs.com'
  version: 0.0.4

servers:
  - url: http://localhost:8090/mic-locations
    description: Localhost
  - url: https://proactivedevs-template-des/mic-locations
    description: DES
  - url: https://proactivedevs-template-pre/mic-locations
    description: PRE
  - url: https://proactivedevs-template-prod/mic-locations
    description: PRO

tags:
  - name: Locations
    description: Operations about locations management

security:
  - basicAuth: []
  - bearerAuth: []

paths:
  /v1/locations/location-types:
    $ref: './v1/services/location-types/location-types-get-all.yml'
  /v1/locations:
    $ref: './v1/services/locations/locations-create.yml'
  /v1/locations/search:
    $ref: './v1/services/locations/locations-search.yml'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
