---
pipeline:
  version: 3

apis:
  - name: "Tenants Events"
    api-spec-type: event
    definition-path: tenants/event
  - name: "Tenants REST API"
    api-spec-type: rest
    definition-path: tenants/rest
  - name: "Provisioning REST API"
    api-spec-type: rest
    definition-path: provisioning/rest
  - name: "Auth REST API"
    api-spec-type: rest
    definition-path: auth/rest
  - name: "Categories REST API"
    api-spec-type: rest
    definition-path: categories/rest
  - name: "Products REST API"
    api-spec-type: rest
    definition-path: products/rest
  - name: "Inventory REST API"
    api-spec-type: rest
    definition-path: inventory/rest
  - name: "Locations REST API"
    api-spec-type: rest
    definition-path: locations/rest
