---
pipeline:
  version: 3

apis:
  - name: "Tenants Events"
    api-spec-type: event
    definition-path: tenants/event
  - name: "Tenants REST API"
    api-spec-type: rest
    definition-path: tenants/rest
  - name: "Tenants Websockets"
    api-spec-type: websocket
    definition-path: tenants/websocket
