openapi: 3.0.3

info:
  title: Categories API
  description: Provides endpoints that allow tenants to manage category information within the system
  contact:
    name: Proactive Devs team
    email: proactivedevs@gmail.com
    url: 'http://proactivedevs.com'
  version: 0.0.2

servers:
  - url: http://localhost:8080/micclients
    description: Localhost
  - url: https://proactivedevs-template-des/micclients
    description: DES
  - url: https://proactivedevs-template-pre/micclients
    description: PRE
  - url: https://proactivedevs-template-prod/micclients
    description: PRO

tags:
  - name: Categories
    description: Operations about Categories management

security:
  - basicAuth: []
  - bearerAuth: []

paths:
  /v1/categories:
    $ref: './v1/services/categories/categories-create.yml'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
