openapi: 3.0.3

info:
  title: Inventory API
  description: Inventory management and movement types
  contact:
    name: Proactive Devs team
    email: proactivedevs@gmail.com
    url: 'http://proactivedevs.com'
  version: 0.0.1

servers:
  - url: http://localhost:8090/mic-inventory
    description: Localhost
  - url: https://proactivedevs-template-des/mic-inventory
    description: DES
  - url: https://proactivedevs-template-pre/mic-inventory
    description: PRE
  - url: https://proactivedevs-template-prod/mic-inventory
    description: PRO

tags:
  - name: MovementTypes
    description: Operations about MovementTypes management

security:
  - basicAuth: []
  - bearerAuth: []

paths:
  /v1/inventory/movement-types:
    $ref: './v1/services/movement-types/movement-types-get-all.yml'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
