openapi: 3.0.3

info:
  title: Inventory API
  description: Inventory management and movement types
  contact:
    name: Proactive Devs team
    email: proactivedevs@gmail.com
    url: 'http://proactivedevs.com'
  version: 0.2.0

servers:
  - url: http://localhost:8090/mic-inventory
    description: Localhost
  - url: https://proactivedevs-template-des/mic-inventory
    description: DES
  - url: https://proactivedevs-template-pre/mic-inventory
    description: PRE
  - url: https://proactivedevs-template-prod/mic-inventory
    description: PRO

tags:
  - name: Inventory
    description: Operations about inventory management and movement types

security:
  - basicAuth: []
  - bearerAuth: []

paths:
  /v1/inventory/movement-types:
    $ref: './v1/services/movement-types/movement-types-get-all.yml'
  /v1/inventory/movement-reasons:
    $ref: './v1/services/movement-reasons/movement-reasons-get-all.yml'
  /v1/movements/inbound:
    $ref: './v1/services/movements/movements-inbound.yml'
  /v1/movements/inbound/receipts/{receiptId}:
    $ref: './v1/services/movements/movements-inbound-receipts-by-id.yml'
  /v1/movements/outbound:
    $ref: './v1/services/movements/movements-outbound.yml'
  /v1/movements/outbound/receipts/{receiptId}:
    $ref: './v1/services/movements/movements-outbound-receipts-by-id.yml'
  /v1/movements/search:
    $ref: './v1/services/movements/movements-search.yml'
  /v1/inventory/search:
    $ref: './v1/services/inventory/inventory-search.yml'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
